object Versions {
  val cats                 = "2.1.1"
  val collectionCompat     = "2.1.6"
  val commonsIo            = "2.6"
  val disciplineScalatest  = "1.0.1"
  val enumeratum           = "1.6.0"
  val enumeratumScalacheck = "1.5.16"
  val imp                  = "0.4.1"
  val libra                = "0.6.0"
  val refined              = "0.9.14"
  val scalacheck           = "1.14.3"
  val scalacheckShapeless  = "1.2.5"
  val scalatest            = "3.1.1"
  val scalaz               = "7.2.30"
  val shapeless            = "2.3.3"
}
