object Versions {
  val cats                 = "2.12.0"
  val collectionCompat     = "2.12.0"
  val commonsIo            = "2.18.0"
  val disciplineScalatest  = "2.3.0"
  val enumeratum           = "1.7.5"
  val enumeratumScalacheck = "1.7.5"
  val imp                  = "0.5.0"
  val libra                = "0.7.0"
  val refined              = "0.11.3"
  val scalacheck           = "1.18.1"
  val scalacheckShapeless  = "1.3.2"
  val scalatest            = "3.2.19"
  val scalaz               = "7.3.8"
  val shapeless            = "2.3.12"
}
