object Versions {
  val cats                 = "1.0.1"
  val commonsIo            = "2.6"
  val contextual           = "1.1.0"
  val discipline           = "0.8"
  val enumeratum           = "1.5.12"
  val enumeratumScalacheck = "1.5.13"
  val imp                  = "0.3.0"
  val jodaConvert          = "1.9.2"
  val joda                 = "2.9.9"
  val libra                = "0.3.0"
  val refined              = "0.8.7"
  val scalacheck           = "1.13.5"
  val scalacheckShapeless  = "1.1.8"
  val scalatest            = "3.0.5"
  val scalaz               = "7.2.19"
  val shapeless            = "2.3.3"
}
